# Generated by Django 3.0.5 on 2021-08-19 09:10

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserObject',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Ник наблюдаемого пользователя')),
                ('activate', models.BooleanField(default=True, verbose_name='Параметр, отвечающие за необходимость обновления данных о пользователе')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Показывает время последнего обновление данных пользователя')),
                ('medias', djongo.models.fields.JSONField(blank=True, default={}, verbose_name='Хранит информацию об ресурсах с главной страницы')),
                ('stories', djongo.models.fields.JSONField(blank=True, default={}, verbose_name='Хранит информацию о ресурсах с историй')),
            ],
        ),
    ]
