# Generated by Django 3.0.5 on 2021-07-22 10:29

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserObject',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('activate', models.BooleanField(default=True)),
                ('medias', djongo.models.fields.JSONField(blank=True, null=True)),
                ('stories', djongo.models.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
